groups:
- name: nodelocaldns
  rules:
  - alert: NodeLocalDNSMetricsDown
    annotations:
      message: Node Local DNS has disappeared from Prometheus target discovery.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-nodelocaldnsmetricsdown
    expr: |
      absent(up{name="node-local-dns-metrics"} == 1)
    for: 2m
    labels:
      severity: critical
  - alert: NodeLocalDNSSetupErrorsHigh
    annotations:
      message: There are {{$labels.errortype}} errors setting up Node Local DNS.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-nodelocaldnssetuperrorshigh
    expr: |
      rate(coredns_nodecache_setup_errors{name="node-local-dns-metrics"}[5m]) > 0
    for: 2m
    labels:
      severity: critical
- name: coredns
  rules:
  - alert: NodeLocalDNSDown
    annotations:
      message: NodeLocalDNS has disappeared from Prometheus target discovery.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-corednsdown
    expr: |
      absent(up{k8s_app="node-local-dns"} == 1)
    for: 15m
    labels:
      severity: critical
  - alert: NodeLocalDNSLatencyHigh
    annotations:
      message: NodeLocalDNS has 99th percentile latency of {{ $value }} seconds for
        server {{ $labels.server }} zone {{ $labels.zone }} .
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-corednslatencyhigh
    expr: |
      histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app="node-local-dns"}[5m])) without(instance, pod)) > 4
    for: 10m
    labels:
      severity: critical
  - alert: NodeLocalDNSErrorsHigh
    annotations:
      message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
        }} of requests.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-corednserrorshigh
    expr: |
      sum(rate(coredns_dns_response_rcode_count_total{k8s_app="node-local-dns",rcode="SERVFAIL"}[5m]))
        /
      sum(rate(coredns_dns_response_rcode_count_total{k8s_app="node-local-dns"}[5m])) > 0.03
    for: 10m
    labels:
      severity: critical
  - alert: NodeLocalDNSErrorsHigh
    annotations:
      message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
        }} of requests.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-corednserrorshigh
    expr: |
      sum(rate(coredns_dns_response_rcode_count_total{k8s_app="node-local-dns",rcode="SERVFAIL"}[5m]))
        /
      sum(rate(coredns_dns_response_rcode_count_total{k8s_app="node-local-dns"}[5m])) > 0.01
    for: 10m
    labels:
      severity: warning
- name: coredns_forward
  rules:
  - alert: NodeLocalDNSForwardLatencyHigh
    annotations:
      message: NodeLocalDNS has 99th percentile latency of {{ $value }} seconds forwarding
        requests to {{ $labels.to }}.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-corednsforwardlatencyhigh
    expr: |
      histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{k8s_app="node-local-dns"}[5m])) without(instance, pod)) > 4
    for: 10m
    labels:
      severity: critical
  - alert: NodeLocalDNSForwardErrorsHigh
    annotations:
      message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
        }} of forward requests to {{ $labels.to }}.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-corednsforwarderrorshigh
    expr: |
      sum(rate(coredns_forward_response_rcode_count_total{k8s_app="node-local-dns",rcode="SERVFAIL"}[5m]))
        /
      sum(rate(coredns_forward_response_rcode_count_total{k8s_app="node-local-dns"}[5m])) > 0.03
    for: 10m
    labels:
      severity: critical
  - alert: NodeLocalDNSForwardErrorsHigh
    annotations:
      message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
        }} of forward requests to {{ $labels.to }}.
      runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-corednsforwarderrorshigh
    expr: |
      sum(rate(coredns_dns_response_rcode_count_total{k8s_app="node-local-dns",rcode="SERVFAIL"}[5m]))
        /
      sum(rate(coredns_dns_response_rcode_count_total{k8s_app="node-local-dns"}[5m])) > 0.01
    for: 10m
    labels:
      severity: warning
