version: 2
jobs:
  build:
    docker:
      - image: csmarchbanks/kubernetes-mixin-build:0.1.2

    working_directory: /go/src/github.com/povilasv/nodelocaldns-mixin
    steps:
      - checkout
      - run: mkdir -p vendor/.tmp
      - run: jb install
      - run: make
